[[hsakmt_roct]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "239b4840ed8cc900b518857a2da897b423afad30"
libc = "glibc"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "ac65c351a61a4c661f1cba9327152b8f6145ea9b88dff0304055fb4982a08295"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v5.2.3+0/hsakmt_roct.v5.2.3.x86_64-linux-gnu-cxx11.tar.gz"
[[hsakmt_roct]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eb46b008b77f2592221323ee7cb6919ca154d7c"
libc = "musl"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "24feba7f5cedd41d17fcd9b725146eba20128848297b4fb04b072403946f1fc4"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v5.2.3+0/hsakmt_roct.v5.2.3.x86_64-linux-musl-cxx11.tar.gz"
