[[hsakmt_roct]]
arch = "x86_64"
git-tree-sha1 = "80906fdc414f038b6fbc74a48e7f00fad6b477b2"
libc = "glibc"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "89cf9b4c577fda148514dbcf5b7a25023348ac2006e33f5f8232cf7cf7969f22"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v4.5.2+0/hsakmt_roct.v4.5.2.x86_64-linux-gnu.tar.gz"
[[hsakmt_roct]]
arch = "x86_64"
git-tree-sha1 = "a2bf5b2cd22416ff073e622f6e65122a3cca9ff1"
libc = "musl"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "0b2aa58978a812fa2a75778ea7b266c0f075b25410bcd62b01647e5c0c894666"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v4.5.2+0/hsakmt_roct.v4.5.2.x86_64-linux-musl.tar.gz"
