[[hsakmt_roct]]
arch = "x86_64"
git-tree-sha1 = "2f1cce1661a40dbdd79d46e4b6332177c03569f5"
libc = "glibc"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "c1717e39242e08314cb140101fb8016b9f2a6be3d29d6fe1d36127a8ac4c5eac"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v3.7.0+0/hsakmt_roct.v3.7.0.x86_64-linux-gnu.tar.gz"
