[[hsakmt_roct]]
arch = "x86_64"
git-tree-sha1 = "edb1d767e880a8c89d963fa3cd306bdb5e0f1468"
libc = "glibc"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "f33300d56c94c08a2b8405a7bed24a228e2162c3896730dcd1afa9afb9b4eac8"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v4.0.0+0/hsakmt_roct.v4.0.0.x86_64-linux-gnu.tar.gz"
[[hsakmt_roct]]
arch = "x86_64"
git-tree-sha1 = "2679573332c4fe5a57db6a45a1756b444103a34f"
libc = "musl"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "d6d70068347f06a3ff1af1d37ae8f95e1e708d1d775623db03e47a100c05c271"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v4.0.0+0/hsakmt_roct.v4.0.0.x86_64-linux-musl.tar.gz"
