[[hsakmt_roct]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88b0a43dbe19cb9cf552ffe8c8a9f285a53002ab"
libc = "glibc"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "0d9a061db87599672e85e873706664c0f83992d3af030be19595bc8633b4ec72"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v5.5.1+0/hsakmt_roct.v5.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[hsakmt_roct]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8be19d9a41bec91765c69de9051bcc65ca8590ce"
libc = "musl"
os = "linux"

    [[hsakmt_roct.download]]
    sha256 = "90968016cd5a9d7e15cd7e5f08737842b379b9193a59de3064e817dfb67b2637"
    url = "https://github.com/JuliaBinaryWrappers/hsakmt_roct_jll.jl/releases/download/hsakmt_roct-v5.5.1+0/hsakmt_roct.v5.5.1.x86_64-linux-musl-cxx11.tar.gz"
