# Autogenerated wrapper script for hsakmt_roct_jll for x86_64-linux-gnu-cxx03
export libhsakmt

using NUMA_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `libhsakmt`
const libhsakmt_splitpath = ["lib", "libhsakmt.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libhsakmt_path = ""

# libhsakmt-specific global declaration
# This will be filled out by __init__()
libhsakmt_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libhsakmt = "libhsakmt.so.1"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"hsakmt_roct")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    # From the list of our dependencies, generate a tuple of all the PATH and LIBPATH lists,
    # then append them to our own.
    foreach(p -> append!(PATH_list, p), (NUMA_jll.PATH_list,))
    foreach(p -> append!(LIBPATH_list, p), (NUMA_jll.LIBPATH_list,))

    global libhsakmt_path = normpath(joinpath(artifact_dir, libhsakmt_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libhsakmt_handle = dlopen(libhsakmt_path)
    push!(LIBPATH_list, dirname(libhsakmt_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    
end  # __init__()

